### ISSUE TITLE
handle static files with better strategy not if/else

### ISSUE THREAD

**Issue by masoudgs** [GAumala/MediaServer#3]
I needed to add a `VideoJS` plugin to the library and i think it'd be better to handle static files dynamically. Everything which placed in `public` directory is public and you don't need to check file names and in case of HTML template files, you must put them in another folder.

https://github.com/GAumala/MediaServer/blob/45702560453a42b04c6e28d2efd8110d4edab5f9/net/StaticAssets.go#L28-L38

**Comment by GAumala** [comment]
Yes, this sounds like a great idea. PRs welcome!
